# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb3e08b03badd1484978bb1909b471d17df740305ce1c01a0272b604d8e9ae9a2e08722ba0467f1eae421463950a9872ec79f3a354a6a032baba35510ab9d5f

test:
  secret_key_base: c895a4a3f31708af2a747432e27d6da75dfd7be68d9e923723fa94c3fad21c267a58518d00022f8dce17d14f8f46597cb4fc1c99c4e2be83425c7ce4db13e002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
