# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc1b509c9c6f946af173cc6c698f83b1d11159c00366602da75f71891580280c9a22f21fc18cd09035321ef67accef521436731c64c32d8425f96af347a237c0

test:
  secret_key_base: 22b19638765b135383551fc61a35606a31436f43c4860b5b254647c884a602a4f842fd8455cc8fff8b248c2ba4bed2df6c6c867b5d63a0c949d722ee0f1a145a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
